spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: orcamentos-mass
  datasource:
    url: ${ENV_DB_URL}
    username: ${ENV_DB_USERNAME}
    password: ${ENV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/sql/inserts_default.sql
server:
  error:
    include-message: never
jwt:
  secret:
    key: ${ENV_JWT_KEY}
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tagsSorter: "alpha"
